name:                radon
version:             0.1.0.0
github:              "nickwanninger/radon"
license:             BSD3
author:              "nickwanninger"
maintainer:          "nickwanninger@gmail.com"
copyright:           "2019 Nick Wanninger"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/radon#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers

library:
  source-dirs: src

executables:
  radon-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - radon

tests:
  radon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - radon
